Feature Manage WishList
atlp-rwanda/dynamites-ecomm-be pull request #112
Opened 2024-05-29 18:58 UTC by 13XAVI

This PR is for user to view and manage my wishlist so that he/she can keep track of products he/she is interested in purchasing in the future

### Description of Task to be completed?
 - [ ] Buyers can add products to their wishlist from product pages or search results.
 - [ ] Buyers can view their wishlist at any time to see all the items they have saved.
 - [ ] Buyer can remove item from wish list.
 - [ ] Implement appropriate error handling and responses ,unit tests and documentation

2024-05-30 08:35 UTC, ambroisegithub commented
Please add your swagger and test screenshot prove and try to test the uncovered lines not tested in your buyer wish-list controller.

2024-05-30 08:41 UTC, jkarenzi approved these changes

2024-05-30 08:44 UTC, jkarenzi requested changes

2024-05-30 08:44 UTC, jkarenzi commented on src/controller/buyerWishlistController.ts
The code coverage of your controller is low (60%). Try to increase it

2024-05-30 08:59 UTC, wayneleon1 approved these changes
Looks Good

2024-05-30 09:02 UTC, wayneleon1 approved these changes, later dismissed

2024-05-30 09:14 UTC, 13XAVI commented on src/controller/buyerWishlistController.ts
code i think codes were lost

2024-06-03 15:46 UTC, jkarenzi submitted a review, later dismissed

2024-06-05 11:55 UTC, jkarenzi approved these changes

2024-06-05 12:00 UTC, ambroisegithub approved these changes
It Looks good for merge!!!

2024-06-05 12:01 UTC, ambroisegithub approved these changes
Good job!!!

2024-06-05 12:15 UTC, merged