#17 Create the workflow CI.
atlp-rwanda/dynamites-ecomm-be pull request #21
Opened 2024-04-25 14:31 UTC by niyibi250

### What does this PR do

we are created the .yml file the describe what to do before push to develop branch(which is default branch) and on pull requests
we are running test script in packege.json then run linting  after we are running build script in the packege.json.

### Description of Task to be completed?

-  install dependencies using ci
-  run `npm test`
-  run linting if present
- run `npm build`
 
### How should this be manually tested?

you can create new branch and try push it to default branch(develop) and see if it run workflow file

2024-04-25 15:20 UTC, wayneleon1 requested changes

2024-04-25 15:20 UTC, wayneleon1 commented on .github/workflows/workflow_for_ecomm.yml
- for testing  the command is `npm run test`
- for testing coverage the command is `npm run test:ci`

2024-04-25 15:25 UTC, niyibi250 commented on .github/workflows/workflow_for_ecomm.yml
ok let me change

2024-04-26 09:11 UTC, wayneleon1 approved these changes

2024-04-26 13:15 UTC, ambroisegithub reviewed
That's is Look Good!!!

2024-04-30 12:14 UTC, merged