pull from develop
atlp-rwanda/dynamites-ecomm-be pull request #53
Opened 2024-05-08 14:35 UTC by Dawaic6

2024-05-10 08:09 UTC, ambroisegithub reviewed
It look good for me!!!

2024-05-10 08:10 UTC, wayneleon1 submitted a review, later dismissed
good job

2024-05-10 08:10 UTC, 13XAVI submitted a review, later dismissed
Great

2024-05-10 08:31 UTC, bertrandshema approved these changes, later dismissed
It looks good.

2024-05-10 11:58 UTC, Habinezajanvier requested changes

2024-05-10 11:58 UTC, Habinezajanvier commented on src/controller/userController.ts
> +}
Please, let's use the middleware with with try catch, to prevent repeating ourselves

2024-05-10 11:58 UTC, Habinezajanvier commented on src/routes/userRoutes.ts
> +route.put('/updateProfile/:id',updateProfile);
Remember to embed your functionality into the errorHandler middleware

2024-05-10 11:58 UTC, Habinezajanvier commented on src/controller/userController.ts
> +  user.password = hashedPassword;
Update other fields but not the password please

2024-05-10 11:58 UTC, Habinezajanvier commented on src/controller/userController.ts
> +}
You have to validate your request body before anything else please, and please separate concerns, can you try to put validations aside to keep our controller clean

2024-05-17 07:58 UTC, wayneleon1 approved these changes
that's look good

2024-05-17 08:48 UTC, bertrandshema approved these changes
This is okay with me

2024-05-17 11:16 UTC, Habinezajanvier approved these changes
LGTM

2024-05-17 11:17 UTC, merged