Implemented product availability get and update
atlp-rwanda/dynamites-ecomm-be pull request #74
Opened 2024-05-18 13:06 UTC by niyobern

# Product Availability Feature

## Summary
This pull request implements a new feature that allows vendors to update and query the availability of their products. Additionally, the product availability is automatically set to false when the quantity reaches zero.

## Changes
- Vendors can now update the availability status of their products.
- Vendors can query the current availability status of their products.
- Added a function that updates product availability when called inside controllers that modify product quantity.

```typescript
const productQuantityWatch = async (product: Product) => {
    const quantity = product.quantity;

    if (quantity > 0) {
        product.isAvailable = true;
    } else {
        product.isAvailable = false;
    }

    await productRepository.save(product)

    return product;
};

## How to Test
1. Update the product availability using the new endpoint.
2. Query the product to verify the updated availability status.
3. Reduce the product quantity to zero and verify that the availability status is automatically set to false.
4.  Increase the product availability from zero and verify that the product availability is set to true.

## Impact
This feature enhances the vendor's ability to manage their products more effectively, providing real-time updates on product availability based on quantity.

## Additional Information
Please ensure to run the updated tests included in this PR to verify that everything is working as expected.

2024-05-18 20:36 UTC, EddyShimwa approved these changes, later dismissed
Looks Good to me!

2024-05-19 16:14 UTC, ambroisegithub commented
Please Add the screenshot of your swagger documentation and testing passing!!!

2024-05-19 19:04 UTC, niyobern commented
> Please Add the screenshot of your swagger documentation and testing passing!!!

@ambroisegithub Swagger documentation screenshot are now included but there is no point in ataching screenshots of tests passing while we have the full log in github actions [https://github.com/atlp-rwanda/dynamites-ecomm-be/actions/runs/9147905258/job/25149832973](url)

2024-05-19 19:12 UTC, ambroisegithub commented
Add testing screenshot of your local one!!!

2024-05-19 19:33 UTC, niyobern commented
> Add testing screenshot of your local one!!!

Here it is but with nothing additional.

![image](https://github.com/atlp-rwanda/dynamites-ecomm-be/assets/85235653/1072d73a-0b03-4489-9fad-c4ea282ac88d)

2024-05-20 06:49 UTC, wayneleon1 approved these changes, later dismissed
Looks Good to me!

2024-05-20 07:07 UTC, ambroisegithub commented
It looks super for me!!!

2024-05-20 09:52 UTC, bertrandshema requested changes
Why do we have files for one just features, if we do this we will have an app with many files. since product availability is about products, please add them in product.test.ts, productcontroller.ts, product.routes.ts and product.doc.ts

2024-05-21 13:37 UTC, niyobern commented
> Why do we have files for one just features, if we do this we will have an app with many files. since product availability is about products, please add them in product.test.ts, productcontroller.ts, product.routes.ts and product.doc.ts

Done

2024-05-22 08:45 UTC, jkarenzi submitted a review, later dismissed

2024-05-22 08:52 UTC, wayneleon1 requested changes

2024-05-22 08:52 UTC, wayneleon1 commented on src/routes/index.ts
can you remove all those commented lines if there are no long  necessary

2024-05-22 08:52 UTC, wayneleon1 submitted a review, later dismissed

2024-05-22 09:15 UTC, bertrandshema reviewed
It is good now.

2024-05-22 09:29 UTC, bertrandshema submitted a review, later dismissed
It is good now

2024-05-23 16:36 UTC, Dawaic6 approved these changes

2024-05-23 16:36 UTC, wayneleon1 approved these changes
Looks good

2024-05-23 16:42 UTC, dushimeemma approved these changes
Good job 💪

2024-05-23 16:43 UTC, merged